antvis/GUI

README.md, __tests__/unit/slider-spec.js, src/index.ts, src/slider/README.md, src/slider/constant.ts, src/slider/index.ts
Can be used in data zoom of G2
=> add Slider component

src/slider/constant.ts, src/slider/handler.ts, src/slider/index.ts
=> refactor(slider): add Handler component, remove image url

.travis.yml, src/slider/handler.ts
=> fix(*): fix ci

src/scroll-bar/index.ts
=> feat(scroll-bar): add mobile event supported

.github/workflows/build.yml, __tests__/unit/util/text.spec.ts, package.json
设置了.github > workflows > build.yml runs on mac
=> chore: changed ./github/build.yml runs on macos

__tests__/unit/ui/sparkline/index.spec.ts, __tests__/unit/ui/sparkline/path.spec.ts, __tests__/unit/ui/sparkline/util.spec.ts, examples/sparkline/basic/demo/area-sparkline.ts, examples/sparkline/basic/demo/area-stack-sparkline.ts, examples/sparkline/basic/demo/basic-sparkbar.ts, examples/sparkline/basic/demo/basic-sparkline.ts, examples/sparkline/basic/demo/stack-sparkbar.ts, src/ui/sparkline/index.ts, src/ui/sparkline/path.ts, src/ui/sparkline/utils.ts
=> Feat sparkline

src/constant.ts, src/types.ts, src/types/index.ts, src/types/styles.ts, src/ui/arrow/index.ts, src/ui/axis/index.ts, src/ui/button/index.ts, src/ui/button/types.ts, src/ui/icon/index.ts, src/ui/icon/types.ts, src/ui/marker/index.ts, src/ui/marker/types.ts, src/ui/scrollbar/index.ts, src/ui/scrollbar/types.ts, src/ui/sheet/index.ts, src/ui/slider/handle.ts, src/ui/slider/index.ts, src/ui/slider/types.ts, src/ui/sparkline/columns.ts, src/ui/sparkline/index.ts, src/ui/sparkline/lines.ts, src/ui/sparkline/path.ts, src/ui/sparkline/types.ts, src/ui/sparkline/utils.ts, src/ui/timeline/index.ts, src/util/style.ts
=> refactor: 修正了type类型的导入导出

src/ui/axis/index.ts, src/ui/button/index.ts, src/ui/icon/index.ts, src/ui/marker/index.ts, src/ui/marker/utils.ts, src/ui/sheet/index.ts, src/ui/slider/index.ts, src/ui/sparkline/index.ts, src/util/index.ts
rt: 修复了marker无法正常显示的问题，修复了type 定义
=> fix: 修复了marker无法正常显示的问题，修复了type 定义

__tests__/unit/ui/legend/continuous-spec.ts, src/ui/legend/base.ts, src/ui/legend/continuous.ts, src/ui/legend/types.ts
=> fix(legend): 修复了导致ci错误的类型定义

src/ui/marker/index.ts, src/ui/marker/symbol.ts
LineSymbols
- line
- dot
- dash
- smooth
- hv
- vh
- hvh
- vhv
=> refactor(marker): 内置了更多symbol

__tests__/unit/ui/marker/index-spec.ts, src/ui/marker/index.ts
=> Fix marker: 修复了marker位置和大小不正确的问题

__tests__/unit/ui/button/index-spec.ts, __tests__/unit/ui/page-navigator/index-spec.ts, __tests__/unit/ui/page-navigator/vertical-spec.ts, docs/api/ui/page-navigator.en.md, docs/api/ui/page-navigator.zh.md, examples/basic-ui/button/demo/disabled-button.ts, examples/basic-ui/button/demo/marker-button.ts, examples/basic-ui/button/demo/meta.json, examples/others/page-navigator/API.en.md, examples/others/page-navigator/API.zh.md, examples/others/page-navigator/demo/basic-page-navigator.ts, examples/others/page-navigator/demo/meta.json, examples/others/page-navigator/demo/vertical-page-navigator.ts, examples/others/page-navigator/index.en.md, examples/others/page-navigator/index.zh.md, examples/others/sparkline/index.en.md, examples/others/sparkline/index.zh.md, src/ui/button/constant.ts, src/ui/button/index.ts, src/ui/button/types.ts, src/ui/index.ts, src/ui/page-navigator/index.ts, src/ui/page-navigator/types.ts
=> Page navigator

__tests__/unit/ui/axis/arc-spec.ts, __tests__/unit/ui/axis/linear-spec.ts, __tests__/unit/ui/legend/continuous-spec.ts, __tests__/unit/ui/legend/vertical-continuous-spec.ts, examples/chart-ui/axis/demo/linear.ts, examples/chart-ui/legend/demo/meta.json, examples/chart-ui/legend/demo/vertical-continuous.ts, src/ui/axis/base.ts, src/ui/axis/constant.ts, src/ui/axis/types.ts, src/ui/button/index.ts, src/ui/legend/base.ts, src/ui/legend/category.ts, src/ui/legend/constant.ts, src/ui/legend/continuous.ts, src/ui/legend/rail.ts, src/ui/tag/index.ts, src/ui/tag/types.ts
Axis: 更新了轴的绘制逻辑以及部分参数定义
Tag: 支持设置对齐方式
Continuous：支持了垂直布局
=> refactor axis、tag、continuous

__tests__/unit/ui/sparkline/path-spec.ts, src/ui/sparkline/path.ts
=> refactor(sparkline): 移除了曲线需要添加 M 0 0才能正确绘制的遗留结局方案

examples/chart-ui/axis/demo/linear.ts, src/ui/axis/arc.ts, src/ui/axis/base.ts
=> refactor(axis): 修改了圆弧坐标轴的文字布局

docs/api/ui/button.zh.md, src/ui/axis/base.ts, src/ui/legend/base.ts, src/ui/legend/category.ts, src/ui/legend/continuous.ts, src/ui/page-navigator/index.ts, src/ui/sparkline/index.ts
* 规范了组件tag命名
* 修复了 button 文档循环依赖问题
=> refactor: 规范了组件tag命名，修复了 button 文档循环依赖问题

__tests__/unit/ui/switch/index-spec.ts, src/ui/switch/index.ts
=> refactor(switch): 按照代码规范，优化 switch 

examples/chart-ui/tooltip/demo/basic-tooltip.ts, examples/chart-ui/tooltip/demo/custom-tooltip.ts, examples/chart-ui/tooltip/demo/mini-tooltip.ts, src/ui/tooltip/index.ts, src/ui/tooltip/types.ts
=> docs(tooltip): 修改了 tooltip examples

examples/others/sparkline/demo/area-sparkline.ts, package.json, src/ui/sparkline/path.ts
=> refactor(sparkline): 变更了sparkline的曲线生成算法，避免出现线条超出上下边界的问题

__tests__/unit/ui/crosshair/circle-crosshair-spec.ts, __tests__/unit/ui/crosshair/line-crosshair-spec.ts, __tests__/unit/ui/crosshair/polygon-crosshair-spec.ts, src/ui/crosshair/base.ts, src/ui/crosshair/circle.ts, src/ui/crosshair/line.ts, src/ui/crosshair/polygon.ts
=> fix(crosshair): 修复了定位计算以及导致 ci 异常的单测

src/ui/button/types.ts
- docs(button): button 组件属性定义梳理
=> refactor(button): Button 组件属性定义梳理

__tests__/unit/ui/checkbox/index-spec.ts, package.json, src/ui/checkbox/constant.ts, src/ui/checkbox/index.ts, src/ui/checkbox/types.ts, src/ui/index.ts
=> feat: add checkbox

__tests__/unit/ui/checkbox/index-spec.ts, src/ui/checkbox/constant.ts, src/ui/checkbox/index.ts
=> feat: checkbox disable

__tests__/unit/ui/poptip/custom-spec.ts, __tests__/unit/ui/poptip/index-spec.ts, docs/api/ui/poptip.en.md, docs/api/ui/poptip.zh.md, examples/chart-ui/poptip/API.en.md, examples/chart-ui/poptip/API.zh.md, examples/chart-ui/poptip/demo/basic-poptip.ts, examples/chart-ui/poptip/demo/content-poptip.ts, examples/chart-ui/poptip/demo/custom-poptip.ts, examples/chart-ui/poptip/demo/meta.json, examples/chart-ui/poptip/demo/update-poptip.ts, examples/chart-ui/poptip/index.en.md, examples/chart-ui/poptip/index.zh.md, package.json, src/ui/index.ts, src/ui/poptip/constant.ts, src/ui/poptip/helpers.ts, src/ui/poptip/index.ts, src/ui/poptip/types.ts
=> feat(Poptip): 添加通用组件 Poptip

__tests__/unit/ui/poptip/custom-spec.ts, __tests__/unit/ui/poptip/index-spec.ts, examples/chart-ui/poptip/demo/axis-poptip.ts, examples/chart-ui/poptip/demo/basic-poptip.ts, examples/chart-ui/poptip/demo/content-poptip.ts, examples/chart-ui/poptip/demo/legend-poptip.ts, examples/chart-ui/poptip/demo/meta.json, examples/chart-ui/poptip/demo/more-direction-poptip.ts, src/ui/poptip/constant.ts, src/ui/poptip/helpers.ts, src/ui/poptip/index.ts
=> feat(poptip): 修改/添加案例 修复poptip 重新改动后出现的一些问题

__tests__/unit/ui/poptip/index-spec.ts, examples/chart-ui/legend/demo/basic-continuous.ts, examples/chart-ui/legend/demo/continuous-event.ts, examples/chart-ui/legend/demo/handle.ts, examples/chart-ui/legend/demo/indicator.ts, examples/chart-ui/legend/demo/various-continuous.ts, examples/chart-ui/slider/demo/meta.json, examples/others/sparkline/demo/area-sparkline.ts, package.json, src/ui/legend/base.ts, src/ui/legend/category.ts, src/ui/legend/constant.ts, src/ui/legend/continuous.ts, src/ui/legend/rail.ts, src/ui/legend/types.ts, src/ui/poptip/constant.ts, src/ui/poptip/index.ts, src/ui/sparkline/index.ts, src/ui/sparkline/path.ts, src/ui/sparkline/types.ts, src/util/shape.ts, src/util/wrapper.ts
=> fix(chart-ui): 修复图表组件的若干问题

package.json
fix pagination issue of legend
=> chore: v0.4.3-alpha.6

src/ui/marker/symbol.ts
=> fix: line marker symbol

package.json, src/ui/legend/category.ts, src/ui/legend/types.ts
=> fix: typings of legend state

src/ui/tooltip/constant.ts, src/ui/tooltip/index.ts
=> feat(tooltip): 优化 tooltip 样式， 参照为 techvis

src/core/gui.ts, src/ui/breadcrumb/index.ts, src/ui/legend/continuous.ts, src/ui/legend/continuousIndicator.ts, src/ui/page-navigator/index.ts, src/ui/sparkline/columns.ts, src/ui/sparkline/lines.ts, src/ui/tag/index.ts, src/ui/text/decoration.ts, src/ui/text/index.ts, src/ui/timeline/button.ts, src/ui/timeline/sliderAxis.ts, src/util/style.ts
* removeChild 和 DOM API 一致，不需要传第二个参数
* 更新 `Animation -> IAnimation` 类型
=> fix: import isNil from util instead of g

tsconfig.build.json, webpack.config.js
as the title: 
* config webpack alias
* config tsconfig baseUrl
=> chore: config tsconfig and webpack for build

package.json
=> chore: update version to 49

src/ui/grid/index.ts
fix: https://yuque.antfin.com/yangtao.yangtao/exgb67/cwv7pw5ew5il49bu#bqVpO
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/15646325/204299856-12c1d61c-0235-402c-9ba0-730e990c92da.png)|<img width="820" alt="image" src="https://user-images.githubusercontent.com/15646325/204299900-b155251f-c2da-46ae-bc5e-319d9de25db1.png">|
=> fix(axis-grid): not render grid duplicate

package.json, src/ui/axis/guides/labels.ts
* G 存在问题，导致设置 transform 设置不正确，需要二次设置
=> fix: fix label transform issue

__tests__/integration/components/navigator/navigator-null.ts, __tests__/integration/components/navigator/navigator-over-pages.ts, __tests__/integration/components/navigator/navigator-update.ts, __tests__/integration/components/navigator/navigator.ts, src/ui/legend/types.ts, src/ui/navigator/index.ts, src/ui/navigator/types.ts
=> refactor: normalize types definition

src/ui/legend/category/item.ts, src/util/shape.ts
- 修复图例不更新颜色的问题 ，详见：https://github.com/antvis/G2/issues/5215
- 注意：这里没有添加测试，GUI 目前添加不了更新相关的单测，这里会在 G2 里面测试。
=> fix(legend): update maker fill

package.json
=> chore: bumps to 0.5.0-alpha.25

docs/api/ui/timebar.zh.md, src/ui/timebar/types.ts
补充时间条文档
时间条
```ts
import { Timebar } from '@antv/gui';
```
| **属性名**            | **类型**                                                       | **描述**                       | **默认值** |
| --------------------- | -------------------------------------------------------------- | ------------------------------ | ---------- |
| type                  | `time`\|`chart`                                                | 时间条类型：时间模式、图表模式 | `time`     |
| playMode              | `acc`\|`slide`                                                 | 播放模式：累计、滑动窗口       | `acc`      |
| values                | `number`\|`number[]`                                           | 选区值                         | `-`        |
| data                  | `{time:number\|Date;value:number}[]`                           | 数据 …
=> docs(timebar): add timebar docs
